### ISSUE TITLE
Slightly larger filesize than fontfacegen

### ISSUE THREAD

**Issue by strarsis** [fontello/ttf2woff#17]
The fonts converted by [`fontfacegen`](https://www.npmjs.com/package/fontfacegen) are slightly smaller (~2kb for a 30kb file, which roughly corresponds to ~7%) than generated by `ttf2woff`. Does the tool perform more optimization or is there an `ttf2woff` option that could yield smaller files?

**Comment by puzrin** [comment]
I can not comment third party tools. Also, since difference is not too big, and `woff` was superseded by `woff2` - no plans to spend time for that.

If you wish, you can experiment with adding `{ level: 9 }` to all deflate calls like [this](https://github.com/fontello/ttf2woff/blob/a4585510d705a0a99cca5ea0b8de240af19eaa71/index.js#L92). But note, i can accept on final result with explained reasons. Micro-optimizations "just for fun" are rejected.
